### ISSUE TITLE
Impossible to download DEFT2021

### ISSUE THREAD

**Issue by jknafou** [DrBenchmark/DrBenchmark#3]
No dl_manager or load_dataset in the code...

**Comment by qanastek** [comment]
Hello,

All the downloading scripts are available on [GitHub](https://github.com/DrBenchmark/DrBenchmark/tree/master/data_loaders_hf) and [Hugging Face](https://huggingface.co/DrBenchmark).

If you have any problem at running the scripts please provide the full error message and try first to upgrade your PyPi `datasets` package.

We performed a wide range of test in a lot of environment and no bug was found.

**Comment by jknafou** [comment]
Hello, I have the last version of datasets (2.20.0), here is the error:

Downloading builder script: 100%|██████████| 24.2k/24.2k [00:00<00:00, 14.3MB/s]
Generating train split: 0 examples [00:00, ? examples/s]
Traceback (most recent call last):
  File "/home/jknafou/.pycharm_helpers/pydevd_asyncio/pydevd_asyncio_utils.py", line 117, in _exec_async_code
    result = func()
  File "<input>", line 1, in <module>
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/load.py", line 2616, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/builder.py", line 1029, in download_and_prepare
    self._download_and_prepare(
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/builder.py", line 1791, in _download_and_prepare
    super()._download_and_prepare(
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/builder.py", line 1124, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/builder.py", line 1629, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/home/jknafou/anaconda3/envs/DrBenchmark/lib/python3.9/site-packages/datasets/builder.py", line 1786, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.exceptions.DatasetGenerationError: An error occurred while generating the dataset
